const vscode=acquireVsCodeApi(),$=id=>document.getElementById(id);let busy=false,messages=[],models=[],agents=[],sessions=[];
for(const type of ['projectChoose','attachFiles','attachFolder','attachmentsClear','connectorFolder','connect','refresh','new','sessionNew','sessionRename','selection','relay','disconnectRelay','stop'])$(type).addEventListener('click',()=>vscode.postMessage({type:type==='new'?'sessionNew':type}));
function renderSessions(m){sessions=m.sessions||[];const list=$('sessionList');if(!list)return;list.replaceChildren();for(const s of sessions){const row=document.createElement('div');row.className='session-row'+(s.active?' active':'');const button=document.createElement('button');button.className='session-item';button.textContent=s.title;button.title=`${s.messageCount}개 메시지`;button.disabled=!!m.busy;button.addEventListener('click',()=>vscode.postMessage({type:'sessionSelect',id:s.id}));const remove=document.createElement('button');remove.className='session-remove';remove.textContent='×';remove.title='대화 삭제';remove.disabled=!!m.busy||sessions.length<2;remove.addEventListener('click',e=>{e.stopPropagation();vscode.postMessage({type:'sessionDelete',id:s.id});});row.append(button,remove);list.append(row);}}
function renderProject(m){
  const c=m.projectContext||{},p=c.project,files=c.files||[],locked=!!(m.busy||m.projectBusy);
  $('projectName').textContent=p?.name||'프로젝트를 선택하세요';$('projectPath').textContent=p?.path||'열린 폴더 또는 다른 디렉터리를 연결할 수 있습니다.';$('projectPath').title=p?.path||'';$('projectChoose').textContent=p?'변경':'프로젝트 선택';
  for(const id of ['projectChoose','attachFiles','attachFolder','attachmentsClear'])$(id).disabled=locked;
  $('send').disabled=locked;$('attachmentSection').hidden=!files.length;$('attachmentSummary').textContent=`${files.length}개 파일 · ${(c.chars||0).toLocaleString()}자`;
  $('attachmentList').replaceChildren();for(const f of files){const row=document.createElement('div');row.className='attachment';const preview=document.createElement('button'),remove=document.createElement('button');preview.className='attachment-name';preview.textContent=f.path;preview.title=`${f.chars.toLocaleString()}자 · 첨부 내용 보기`;preview.disabled=locked;preview.addEventListener('click',()=>vscode.postMessage({type:'attachmentPreview',path:f.path}));remove.textContent='×';remove.setAttribute('aria-label',f.path+' 첨부 빼기');remove.disabled=locked;remove.addEventListener('click',()=>vscode.postMessage({type:'attachmentRemove',path:f.path}));row.append(preview,remove);$('attachmentList').append(row);}
}
function choices(){const value=$('model').value;return {model:value.startsWith('model:')?value.slice(6):'',agent:value.startsWith('agent:')?value.slice(6):'',mode:$('mode').value,approvalMode:$('approvalMode').value};}
function send(){const message=$('prompt').value.trim(),value=$('model').value;if(!message||busy||!value)return;vscode.postMessage({type:'send',message,...choices()});}
$('send').addEventListener('click',send);$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send();}});
$('model').addEventListener('change',()=>{const agent=$('model').value.startsWith('agent:');$('mode').disabled=agent;if(agent)$('mode').value='default';vscode.postMessage({type:'choices',...choices()});});$('mode').addEventListener('change',()=>vscode.postMessage({type:'choices',...choices()}));$('approvalMode').addEventListener('change',()=>vscode.postMessage({type:'choices',...choices()}));
function connection(m){$('dot').className=m.connected?'online':'';$('connection').textContent=m.error|| (m.connected?'학교 브라우저 연결됨':'브라우저 연결 대기');$('relayState').textContent=m.relay?'외부 MCP 연결됨 · 도구별 승인':'외부 MCP 연결 안 됨';const tool=$('toolState');if(!tool||!m.projectContext)return;const project=m.projectContext.project,agent=m.state?.agent;tool.classList.toggle('offline',!project||!m.relay);tool.textContent=!project?'프로젝트를 선택하세요':m.relay?(agent?'MCP 프로젝트 도구 사용 가능 · '+(m.agents?.find(a=>a.id===agent)?.name||'에이전트'):'MCP 연결됨 · MCP 에이전트를 선택하세요'):'MCP 중계 연결 필요';}
function renderText(container,text){const chunks=String(text||'').split(/(```[^\n]*\n[\s\S]*?```)/g);for(const chunk of chunks){if(chunk.startsWith('```')){const first=chunk.indexOf('\n'),code=chunk.slice(first+1,-3),wrap=document.createElement('div'),label=document.createElement('div'),pre=document.createElement('pre'),button=document.createElement('button');label.className='code-label';label.textContent=chunk.slice(3,first)||'code';button.textContent='코드 복사';button.addEventListener('click',()=>navigator.clipboard.writeText(code).catch(()=>{}));label.append(button);pre.textContent=code;wrap.append(label,pre);container.append(wrap);}else{const p=document.createElement('div');p.className='prose';p.textContent=chunk;container.append(p);}}}
function render(){const main=$('messages');main.replaceChildren();if(!messages.length){const empty=document.createElement('section');empty.className='empty';const title=document.createElement('h2');title.textContent='학교 AI와 함께 코딩하세요';const p=document.createElement('p');p.textContent='Astra · Fable · 학교 에이전트\n브라우저를 연결하고 모델을 불러오면 시작할 수 있어요.';empty.append(title,p);main.append(empty);}for(const m of messages){const article=document.createElement('article');article.className=m.role;const title=document.createElement('div');title.className='message-role';title.textContent=m.role==='user'?'나':'학교 AI';const content=document.createElement('div');content.className='content';renderText(content,m.text);article.append(title,content);if(m.contextFiles?.length){const info=document.createElement('small');info.className='message-context';info.textContent=(m.project||'프로젝트')+' · '+m.contextFiles.map(f=>f.path).join(', ');article.append(info);}if(m.status){const status=document.createElement('small');status.className='message-status';status.textContent=m.status+(m.model?' · '+m.model:'');article.append(status);}if(m.attachments?.length){const hint=document.createElement('small');hint.textContent='첨부 결과는 학교 웹 대화에서 확인하세요.';article.append(hint);}main.append(article);}main.scrollTop=main.scrollHeight;}
window.addEventListener('message',({data:m})=>{if(m.type==='state'){models=m.models;agents=m.agents;messages=m.state.messages;busy=m.busy;connection(m);renderSessions(m);$('model').replaceChildren();const selected=m.state.agent?'agent:'+m.state.agent:'model:'+m.state.model;for(const [label,items,prefix]of [['모델',models.filter(x=>x.available!==false),'model:'],['에이전트',agents,'agent:']]){if(!items.length)continue;const group=document.createElement('optgroup');group.label=label;for(const x of items){const option=document.createElement('option');option.value=prefix+x.id;option.textContent=x.display_name||x.name||x.id;group.append(option);}$('model').append(group);}if([...$('model').options].some(o=>o.value===selected))$('model').value=selected;$('mode').value=m.state.mode;$('approvalMode').value=m.state.approvalMode||'ask';$('mode').disabled=!!m.state.agent||busy;$('approvalMode').disabled=busy;$('model').disabled=busy;$('send').disabled=busy;$('new').disabled=busy;$('sessionNew').disabled=busy;$('sessionRename').disabled=busy;$('stop').hidden=!busy;renderProject(m);render();}
if(m.type==='stream'){const last=messages.at(-1);if(last?.role==='assistant'){last.text=m.text;last.status=m.status;render();}}
if(m.type==='connection')connection(m);
if(m.type==='selection'){$('prompt').value+=m.text;$('prompt').focus();}
if(m.type==='accepted')$('prompt').value='';
if(m.type==='notice'){$('notice').hidden=false;$('notice').textContent=m.text;}
});vscode.postMessage({type:'ready'});
