const esbuild = require('esbuild');
const fs = require('node:fs');
const {browserWorker}=require('../src/browser-worker.cjs');
fs.writeFileSync('chrome-extension/worker-main.js',`// Generated by npm run build.\nvoid (${browserWorker.toString()})(window.__schoolCodeConnectorPort || 18766);\n`);
Promise.all([
  esbuild.build({entryPoints:['src/extension.cjs'],outfile:'dist/extension.cjs',bundle:true,platform:'node',target:'node20',external:['vscode']}),
  esbuild.build({entryPoints:['src/relay.cjs'],outfile:'dist/relay.cjs',bundle:true,platform:'node',target:'node22'})
]).catch(()=>process.exit(1));
