const vscode=require('vscode');
function panelHtml(webview,extensionUri,nonce){const js=webview.asWebviewUri(vscode.Uri.joinPath(extensionUri,'media','panel.js')),css=webview.asWebviewUri(vscode.Uri.joinPath(extensionUri,'media','panel.css'));return `<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src ${webview.cspSource}; script-src 'nonce-${nonce}';"><link rel="stylesheet" href="${css}"><title>School Code</title></head><body>
<header><div class="brand"><span class="logo">K</span><div><strong>School Code</strong><small>KOREATECH · 나의 코딩 공간</small></div></div><div class="header-actions"><button id="sessionRename" title="대화 이름 변경">이름</button><button id="new" title="새 대화">＋</button></div></header>
<section class="sessions-card" aria-label="대화 세션"><div class="sessions-heading"><strong>대화 세션</strong><button id="sessionNew">＋ 새 대화</button></div><div id="sessionList"></div></section>
<section class="project-card" aria-label="연결된 프로젝트"><div class="project-top"><div><small>연결된 프로젝트</small><strong id="projectName">프로젝트 선택</strong></div><button id="projectChoose">변경</button></div><div id="projectPath" class="project-path"></div><p>연결된 폴더는 전체를 업로드하지 않습니다. MCP 에이전트가 필요한 파일만 검색·읽습니다.</p><div id="toolState" class="tool-state">프로젝트 도구 대기</div><div class="project-actions"><button id="attachFiles">＋ 파일 첨부(보조)</button><button id="attachFolder">＋ 폴더에서 선택</button></div></section>
<div class="connection"><span id="dot"></span><span id="connection">브라우저 연결 대기</span><button id="connect">브라우저 연결</button></div>
<section class="mcp-card" aria-label="MCP 카탈로그"><div class="mcp-heading"><div><small>MCP 카탈로그</small><strong>연결할 도구 선택</strong></div><div><button id="mcpSite">사이트</button><button id="mcpAdd">＋ MCP 추가</button></div></div><div id="mcpList"><p class="mcp-empty">등록된 MCP를 불러오는 중…</p></div><p class="mcp-help">토큰은 VS Code SecretStorage에 저장됩니다. 외부 MCP 서버는 학교 에이전트 카탈로그에서도 활성화해야 합니다.</p></section>
<details id="setup"><summary>연결 및 외부 MCP</summary><p>Chrome에 School Code Connector를 설치한 뒤 학교 AI 탭을 열어 두세요. 학교 인증 정보는 브라우저 밖으로 보내지 않습니다.</p><button id="connectorFolder">Chrome 확장 폴더 열기</button><button id="refresh">모델·에이전트 새로고침</button><button id="relay">외부 MCP 연결</button><button id="disconnectRelay">MCP 해제</button><p id="relayState">외부 MCP 연결 안 됨</p><hr><p>에이전트가 사용할 연결을 설정하세요. Notion은 읽기 전용이고 Unity CLI는 선택한 프로젝트 안에서만 실행됩니다.</p><button id="notionConfigure">Notion 연결 설정</button><button id="notionDisconnect">Notion 연결 해제</button><button id="unityConfigure">Unity CLI 경로 설정</button><button id="unityEditorConfigure">Unity Editor 자동 준비</button></details>
<div class="selectors"><label>모델<select id="model"><option value="">브라우저 연결 후 새로고침</option></select></label><label>에이전트<select id="agent"><option value="">브라우저 연결 후 새로고침</option></select></label><label>응답 방식<select id="mode"><option value="default">기본 응답</option><option value="fast">빠른 응답</option><option value="deep">깊은 응답</option><option value="direct">다이렉트</option></select></label><label>도구 승인<select id="approvalMode"><option value="ask">매번 확인</option><option value="read">읽기는 자동 승인 · 수정은 확인</option><option value="full">모두 자동 승인</option></select></label><label class="checkbox-setting"><span>컨텍스트 압축</span><input id="contextCompaction" type="checkbox"></label><label>압축 기준<select id="compactionThreshold"><option value="32000">약 3.2만자</option><option value="60000">약 6만자</option><option value="90000">약 9만자</option></select></label></div>
<div id="notice" role="status" hidden></div><main id="messages" aria-label="대화"></main>
<footer><section id="attachmentSection" hidden aria-label="전송할 첨부 파일"><div class="attachment-heading"><span id="attachmentSummary"></span><button id="attachmentsClear">모두 빼기</button></div><div id="attachmentList"></div><small>직접 첨부는 MCP를 사용할 수 없는 일반 모델의 보조 수단입니다.</small></section><div class="composer"><textarea id="prompt" rows="4" placeholder="프로젝트에 대해 질문하세요…" aria-label="메시지"></textarea><div class="actions"><button id="selection" title="선택 코드를 입력창에 추가">＋ 선택 코드</button><span>Ctrl+Enter 전송</span><button id="stop" hidden>중단</button><button id="send" class="primary">전송 ↑</button></div></div><small>MCP 도구를 사용하려면 MCP가 연결된 학교 에이전트를 선택하세요.</small></footer><script nonce="${nonce}" src="${js}"></script></body></html>`;}
module.exports={panelHtml};
