// Exercises the real extension coordinator using a VS Code API double.
// Native extension-host activation is a separate check; this is not claimed as a UI test.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createRequire}=require('node:module'),{randomBytes}=require('node:crypto');
const {BrowserBridge}=require('../src/bridge.cjs');
const {createRelay}=require('../src/relay.cjs');
const {Client}=require('@modelcontextprotocol/sdk/client/index.js');
const {StreamableHTTPClientTransport}=require('@modelcontextprotocol/sdk/client/streamableHttp.js');
const {sha}=require('../src/workspace.cjs');
const dispose=()=>({dispose(){}});
async function until(check){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,20));}throw Error('Test condition timed out');}
test('extension: chat stream, conversation continuation, approved edits, refusal and stale hash',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'school-ext-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.writeFile(path.join(root,'hello.txt'),'hello');
  const mcpToken=randomBytes(32).toString('hex'),workerToken=randomBytes(32).toString('hex'),relay=createRelay({mcpToken,workerToken,port:0});const address=await relay.listen(),url=`http://127.0.0.1:${address.port}`;t.after(()=>relay.close());
  const commands=new Map(),posts=[],errors=[],inputs=[url,workerToken],ctx={subscriptions:[],extensionUri:'extension',workspaceState:{get:(k,f)=>f,update:async()=>{}},secrets:{get:async()=>null,store:async()=>{}}};let provider,handler,bridge,approved=true,approvalHook=null,approvalCount=0;
  const uri=p=>({fsPath:p,scheme:'file',toString:()=>p});
  class Edit{constructor(){this.edits=[];}createFile(u,o){this.edits.push({kind:'create',uri:u,options:o});}replace(u,r,content){this.edits.push({kind:'replace',uri:u,content});}}
  const vscode={Uri:{parse:uri,file:uri,joinPath:(base,...p)=>uri([base,...p].join('/'))},Range:class{},WorkspaceEdit:Edit,
    env:{clipboard:{writeText:async()=>{}},openExternal:async()=>true},
    window:{createOutputChannel:()=>({appendLine(){},dispose(){}}),showInformationMessage:async()=>{},showErrorMessage:e=>errors.push(e),showWarningMessage:async()=>{approvalCount++;if(approvalHook)await approvalHook();return approved?'승인':undefined;},showInputBox:async()=>inputs.shift(),showTextDocument:async()=>{},registerWebviewViewProvider:(id,p)=>{provider=p;return dispose();}},
    workspace:{isTrusted:true,workspaceFolders:[{name:'fixture',uri:uri(root)}],textDocuments:[],getConfiguration:()=>({get:(key,f)=>key==='bridgePort'?0:f}),registerTextDocumentContentProvider:()=>dispose(),
      openTextDocument:async u=>({uri:u,getText:()=>'',positionAt:i=>i,save:async()=>true}),
      applyEdit:async edit=>{for(const e of edit.edits){if(e.kind==='create')await fs.writeFile(e.uri.fsPath,'',{flag:'wx'});else await fs.writeFile(e.uri.fsPath,e.content);}return true;}},
    commands:{registerCommand:(id,fn)=>{commands.set(id,fn);return dispose();},executeCommand:async()=>{}}
  };
  const requireLocal=createRequire(path.resolve(__dirname,'../src/extension.cjs'));
  const module={exports:{}};vm.runInNewContext(await fs.readFile(path.resolve(__dirname,'../src/extension.cjs'),'utf8'),{module,exports:module.exports,require:id=>id==='vscode'?vscode:id==='./panel.cjs'?{panelHtml:()=>'<html></html>'}:id==='./bridge.cjs'?{BrowserBridge:class extends BrowserBridge{constructor(port){super(port);bridge=this;}}}:requireLocal(id),Buffer,URL,fetch,AbortController,AbortSignal,setInterval,clearInterval,setTimeout,clearTimeout,console});
  module.exports.activate(ctx);t.after(()=>ctx.subscriptions.forEach(s=>s.dispose()));await until(()=>bridge.server?.listening);
  provider.resolveWebviewView({webview:{options:{},postMessage:m=>posts.push(structuredClone(m)),onDidReceiveMessage:fn=>{handler=fn;return dispose();}},onDidDispose:()=>dispose()});
  const base=`http://127.0.0.1:${bridge.port}`,headers={Origin:'https://ai.koreatech.ac.kr',Authorization:'Bearer '+bridge.key,'Content-Type':'application/json'};
  await fetch(base+'/worker/heartbeat',{headers});
  async function nextJob(){return (await fetch(base+'/worker/poll',{headers})).json();}
  async function event(data){await fetch(base+'/worker/event',{method:'POST',headers,body:JSON.stringify(data)});}
  await handler({type:'send',message:'/goal Fix the player movement bug'});
  let localState=posts.filter(p=>p.type==='state').at(-1);assert.equal(localState.state.goal.text,'Fix the player movement bug');assert.equal(localState.state.goal.status,'active');
  await handler({type:'send',message:'/goal done'});localState=posts.filter(p=>p.type==='state').at(-1);assert.equal(localState.state.goal.status,'completed');
  await handler({type:'send',message:'/goal Verify the fix with tests'});
  const refreshing=handler({type:'refresh'});
  for(const result of [{items:[{id:'gpt-6-astra',available:true,high_quality:true}]},{items:[]},{items:[]}]){const job=await nextJob();await event({id:job.id,result,done:true});}await refreshing;
  vscode.window.showOpenDialog=async()=>[uri(path.join(root,'hello.txt'))];
  await handler({type:'attachFiles'});assert.equal(posts.filter(p=>p.type==='state').at(-1).projectContext.files[0].path,'hello.txt');
  const sending=handler({type:'send',message:'hello',model:'gpt-6-astra',mode:'direct'});const job=await nextJob();assert.equal(job.body.direct,true);assert.equal(job.body.conversation_id,undefined);assert(job.body.message.includes('hello.txt'));assert(job.body.message.includes('[현재 작업 목표]'));assert(job.body.message.includes('Verify the fix with tests'));assert(job.body.message.includes('프로젝트 파일과 도구 결과를 유일한 사실로'));assert(job.body.message.includes('[사용자 요청]'));assert(!job.body.message.includes(root));assert.equal(posts.filter(p=>p.type==='state').at(-1).projectContext.files.length,0);
  await event({id:job.id,chunk:'data: {"type":"start","conversation_id":"test-conversation"}\n\ndata: {"type":"delta","content":"안녕"}\n\ndata: {"type":"done","model_id":"gpt-6-astra"}\n\n'});await event({id:job.id,done:true});await sending;let state=posts.filter(p=>p.type==='state').at(-1);assert.equal(state.state.messages.at(-1).text,'안녕');assert.equal(state.state.conversationId,'test-conversation');
  const second=handler({type:'send',message:'continue',model:'gpt-6-astra',mode:'default'});const j2=await nextJob();assert.equal(j2.body.conversation_id,'test-conversation');await handler({type:'stop'});await second;state=posts.filter(p=>p.type==='state').at(-1);assert.equal(state.busy,false);assert.match(state.state.messages.at(-1).status,/중단/);
  await commands.get('schoolCode.relay')();await until(()=>posts.some(p=>p.type==='state'&&p.relay));
  const client=new Client({name:'extension-test',version:'1'});t.after(()=>client.close());await client.connect(new StreamableHTTPClientTransport(new URL(url+'/mcp'),{requestInit:{headers:{Authorization:'Bearer '+mcpToken}}}));
  const approvalsBeforeInfo=approvalCount;const info=await client.callTool({name:'workspace_info',arguments:{}});const infoData=JSON.parse(info.content[0].text);assert.equal(approvalCount,approvalsBeforeInfo);assert.equal(infoData.tools.length,48);for(const tool of ['save_image_asset','read_image','list_model_assets','read_model_metadata','unity_capture_scene','unity_capture_game','unity_model_preview','unity_play','unity_project_status','unity_add_component','unity_instantiate_prefab','unity_assign_material','unity_set_animator_parameter'])assert(infoData.tools.includes(tool),tool);assert.equal(infoData.root_isolation,true);assert.equal(infoData.instructions_missing,false);assert.equal(infoData.instructions_setup.created,true);assert.equal(infoData.instructions_setup.automatic,true);assert.deepEqual(infoData.instruction_files,['AGENTS.md']);assert.match(await fs.readFile(path.join(root,'AGENTS.md'),'utf8'),/created automatically/);assert.deepEqual(infoData.skills.skills,[]);assert.equal(infoData.limits.image_max_bytes,16*1024*1024);assert.equal(infoData.limits.model_metadata_max_bytes,64*1024*1024);
  const directory=await client.callTool({name:'create_directory',arguments:{path:'Generated/Textures'}});assert(!directory.isError,directory.content?.[0]?.text);assert.equal((await fs.stat(path.join(root,'Generated/Textures'))).isDirectory(),true);
  await fs.writeFile(path.join(root,'asset.bin'),Buffer.from([0,1,2]));const asset=await client.callTool({name:'read_asset_metadata',arguments:{path:'asset.bin'}});const assetData=JSON.parse(asset.content[0].text);assert.equal(assetData.is_text,false);assert.equal(assetData.size,3);const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');await fs.writeFile(path.join(root,'preview.png'),png);const visuals=await client.callTool({name:'list_visual_assets',arguments:{}});const visualsData=JSON.parse(visuals.content[0].text);assert.deepEqual(visualsData.assets.map(a=>a.path),['preview.png']);const image=await client.callTool({name:'read_image',arguments:{path:'preview.png'}});assert.equal(image.content.length,2);const imageMetadata=JSON.parse(image.content[0].text);assert.equal(imageMetadata.width,1);assert.equal(image.content[1].type,'image');assert.equal(image.content[1].mimeType,'image/png');assert.equal(image.content[1].data,png.toString('base64'));const imageAgain=await client.callTool({name:'read_image',arguments:{path:'preview.png'}});assert.equal(JSON.parse(imageAgain.content[0].text).cache_hit,true);
  const read=await client.callTool({name:'read_file',arguments:{path:'hello.txt'}});assert.equal(JSON.parse(read.content[0].text).sha256,sha('hello'));
  const saveImage=client.callTool({name:'save_image_asset',arguments:{file_id:'generated-image-1',path:'Generated/generated.png'}});const imageJob=await nextJob();assert.equal(imageJob.route,'/chat/uploads/generated-image-1');await event({id:imageJob.id,result:{base64:png.toString('base64'),contentType:'image/png',size:png.length},done:true});const savedImage=await saveImage;const savedImageData=JSON.parse(savedImage.content[0].text);assert.equal(savedImageData.saved,true);assert.equal(savedImageData.path,'Generated/generated.png');assert.equal(savedImageData.width,1);assert.equal(await fs.readFile(path.join(root,'Generated/generated.png'),'base64'),png.toString('base64'));
  const unityInfo=await client.callTool({name:'unity_project_info',arguments:{}});assert.equal(JSON.parse(unityInfo.content[0].text).name,path.basename(root));
  const edit=await client.callTool({name:'propose_edit',arguments:{path:'hello.txt',content:'updated',expected_sha256:sha('hello'),change_summary:'인사 문구를 갱신',verification_plan:'관련 테스트 실행'}});assert(!edit.isError,edit.content[0].text);const editData=JSON.parse(edit.content[0].text);assert.equal(editData.change_summary,'인사 문구를 갱신');assert.equal(editData.verification_plan,'관련 테스트 실행');assert.equal(editData.change_stats.broad_change,false);assert.equal(await fs.readFile(path.join(root,'hello.txt'),'utf8'),'updated');
  const stale=await client.callTool({name:'propose_edit',arguments:{path:'hello.txt',content:'bad',expected_sha256:sha('hello')}});assert(stale.isError);assert.equal(await fs.readFile(path.join(root,'hello.txt'),'utf8'),'updated');
  approved=false;const denied=await client.callTool({name:'read_file',arguments:{path:'hello.txt'}});assert(denied.isError);assert.match(denied.content[0].text,/거절/);approved=true;
  approvalHook=async()=>{await fs.writeFile(path.join(root,'hello.txt'),'user edit during preview');approvalHook=null;};const raced=await client.callTool({name:'propose_edit',arguments:{path:'hello.txt',content:'wrong overwrite',expected_sha256:sha('updated')}});assert(raced.isError);assert.equal(await fs.readFile(path.join(root,'hello.txt'),'utf8'),'user edit during preview');
  const created=await client.callTool({name:'propose_edit',arguments:{path:'new.txt',content:'new content'}});assert(!created.isError,created.content[0].text);assert.equal(await fs.readFile(path.join(root,'new.txt'),'utf8'),'new content');
  await commands.get('schoolCode.disconnectRelay')();assert.deepEqual(errors,[]);
});

test('extension routes workflow agents through workflow SSE and records steps',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'school-workflow-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
  const commands=new Map(),posts=[],errors=[],ctx={subscriptions:[],extensionUri:'extension',workspaceState:{get:(k,f)=>f,update:async()=>{}},secrets:{get:async()=>null,store:async()=>{}}};let provider,handler,bridge;
  const uri=p=>({fsPath:p,scheme:'file',toString:()=>p});
  const vscode={Uri:{parse:uri,file:uri,joinPath:(base,...p)=>uri([base,...p].join('/'))},Range:class{},WorkspaceEdit:class{},env:{clipboard:{writeText:async()=>{}},openExternal:async()=>true},window:{createOutputChannel:()=>({appendLine(){},dispose(){}}),showInformationMessage:async()=>{},showErrorMessage:e=>errors.push(e),showWarningMessage:async()=> '승인',showInputBox:async()=>'',showTextDocument:async()=>{},registerWebviewViewProvider:(id,p)=>{provider=p;return {dispose(){}};}},workspace:{isTrusted:true,workspaceFolders:[{name:'fixture',uri:uri(root)}],textDocuments:[],getConfiguration:()=>({get:(key,f)=>key==='bridgePort'?0:f}),registerTextDocumentContentProvider:()=>({dispose(){}}),openTextDocument:async u=>({uri:u,getText:()=>'',positionAt:i=>i,save:async()=>true}),applyEdit:async()=>true},commands:{registerCommand:(id,fn)=>{commands.set(id,fn);return {dispose(){}};},executeCommand:async()=>{}}};
  const requireLocal=createRequire(path.resolve(__dirname,'../src/extension.cjs'));const module={exports:{}};
  vm.runInNewContext(await fs.readFile(path.resolve(__dirname,'../src/extension.cjs'),'utf8'),{module,exports:module.exports,require:id=>id==='vscode'?vscode:id==='./panel.cjs'?{panelHtml:()=>'<html></html>'}:id==='./bridge.cjs'?{BrowserBridge:class extends BrowserBridge{constructor(port){super(port);bridge=this;}}}:requireLocal(id),Buffer,URL,fetch,AbortController,AbortSignal,setInterval,clearInterval,setTimeout,clearTimeout,console});
  module.exports.activate(ctx);t.after(()=>ctx.subscriptions.forEach(s=>s.dispose()));await until(()=>bridge.server?.listening);provider.resolveWebviewView({webview:{options:{},postMessage:m=>posts.push(structuredClone(m)),onDidReceiveMessage:fn=>{handler=fn;return {dispose(){}};}},onDidDispose:()=>{}});
  const base=`http://127.0.0.1:${bridge.port}`,headers={Origin:'https://ai.koreatech.ac.kr',Authorization:'Bearer '+bridge.key,'Content-Type':'application/json'};await fetch(base+'/worker/heartbeat',{headers});async function nextJob(){return (await fetch(base+'/worker/poll',{headers})).json();}async function event(data){await fetch(base+'/worker/event',{method:'POST',headers,body:JSON.stringify(data)});}
  const refreshing=handler({type:'refresh'});for(const result of [{items:[{id:'gpt-6-sol',available:true}]},{items:[{id:'school-agent',name:'School Code 프로젝트 개발자',has_workflow:true}]},{items:[]}]){const job=await nextJob();await event({id:job.id,result,done:true});}await refreshing;
  const sending=handler({type:'send',message:'프로젝트를 분석해줘',agent:'school-agent',mode:'default'});const job=await nextJob();assert.equal(job.route,'/agents/school-agent/workflow/run');assert.equal(job.body.stream,true);assert.match(job.body.input_text,/프로젝트를 분석해줘/);
  await event({id:job.id,chunk:'data: {"type":"run_start","run_id":"run-1"}\n\ndata: {"type":"node_output","node_name":"MCP 도구 실행","output":"파일을 확인했습니다."}\n\ndata: {"type":"run_end","output":{"outputs":[{"value":"최종 답변"}]}}\n\n'});await event({id:job.id,done:true});await sending;
  const state=posts.filter(p=>p.type==='state').at(-1);const answer=state.state.messages.at(-1);assert.equal(answer.status,'완료');assert.equal(answer.text,'최종 답변');assert.equal(answer.steps.length,3);assert.deepEqual(errors,[]);
});
